### ISSUE TITLE
Image logo disparait

### ISSUE THREAD

**Issue by marwa-mohamed-dev** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#10]
Lorsqu'on est à l'intérieur de référenciel, si on rentre dans Article ou Individu, l'image n'est plus là

**Comment by GomesLucie** [comment]
**Problème trouvé:** http://localhost:3000/referentiel/Fenouille.png
Lorsque l'on est dans une sous page, il y a un / en trop qui empêche l'application de trouver l'image

**Comment by marwa-mohamed-dev** [comment]
![image](https://user-images.githubusercontent.com/47494409/113273211-b7db6000-92dc-11eb-8f57-2c02f5f16bda.png)
![image](https://user-images.githubusercontent.com/47494409/113273312-d0e41100-92dc-11eb-881b-15fc7b510f9a.png)

**Comment by AstridWinkler** [comment]
Résolution : Il fallait remonter plus dans le chemin qui nous menait à l'image puisqu'on s'en écartait avec le dossier Référentiel dans les views.
Il fallait donc, dans nav, appeler l'image du logo Fenouil de cette manière src="../Fenouille.png" au lieu de src="Fenouille.png".

**Comment by GomesLucie** [comment]
Le problème réapparait lorsque l'on affiche les détail d'un article spécifique (lien ci-dessous):
http://localhost:3000/referentiel/Article/606641b7d14e51622ce4fb03

Proposition résolution: Modifier le nom du lien, on réduit à 2 éléments après le 3000/ pour que le serveur puisse trouver l'image

**Comment by GomesLucie** [comment]
même soucis lors de la modification d'un individu:
http://localhost:3000/referentiel/Individu/60663cc967d3c70ba8f533c0

**Comment by GomesLucie** [comment]
J'ai modifié les href des pages ModificationArticle, ModificationIndividu, Article et Individu (en enlevant un /) ce qui a permi aux pages de trouver l'image du logo.
