### ISSUE TITLE
Empiètement de la page "créer une commande" sur footer

### ISSUE THREAD

**Issue by GomesLucie** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#12]
Lorsque l'on ajoute plus de 10 articles à une commande, des éléments du formulaire empiètent sur le footer.

**Comment by LouiseW98** [comment]
Résolution de l'issue lors d'une modification de la page commande.
Lorsque l'on a enlevé le grid à la .page et qu'on l'a mit uniquement au form, le problème était résolu.
