### ISSUE TITLE
Test Création d'un Individu

### ISSUE THREAD

**Issue by LouiseW98** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#20]
Test de la commande "Création d'un individu" dans le module "Administration du référentiel".

-Vérification que les champs sont fonctionnels
-Vérification que tous les champs sont présents
-Vérification des champs obligatoires
-Vérification que l'individu est bien enregistré dans la base de données

**Comment by GomesLucie** [comment]
Test réalisé:

-tous les champs nécessaires sont présents
-tous les champs obligatoires sont required (impossible de valiser sinon)
-lorsque tous les champs sont convenablement remplis, l'individus s'enregistre bien dans la base de donnée

**_Problèmes:_**
-dans catégorie, la première option (qui n'en est pas une normalement) permet la création de l'article (voir pour définir la première option comme non valide)
-input de tel et numéro de voie sont des texts et non des nombres (voir pour peut être autorisé que certains caractère=chiffres) -> lorsque l'on met des lettres induit une erreur dans le terminal

**Comment by GomesLucie** [comment]
Modification du input pour le téléphone : type='tel' avec un pattern correspondant au téléphone français (commençant par un 0 et contenant ensuite 9 chiffres entre 0 et 9).
Ajout d'un pattern pour le numéro de voie  et code postal : accepte uniquement des numéros
Modification du type de input pour le mail : type='email'

**_Problème:_** le pattern donné par le type='email' n'est pas encore complet (on peut valider l'email sans avoir de .com par exemple)

**Comment by GomesLucie** [comment]
Modification des propriétés de l'option catégorie : "disabled" pour qu'elle ne soit pas sélectionnable (grisée) et "selected" pour qu'elle s'affiche par défault

**_Problème:_** 
Lorsque on ne sélectionne pas d'autre option de "catégorie", le formulaire ne s'envoit pas (ce qui ets bien) mais il n'y a pas de message d'erreur sur la page internet (mais le terminal affiche le message d'erreur et la page tourne en boucle)

**Comment by marwa-mohamed-dev** [comment]
Si on ne choisit pas une catégorie, on a une erreur qui s'affiche. 

Proposition : ajouter un default.
Par exemple : 
categoriePro : {
        type : String,
        required: true,
        default: 'inconnu'
    },

**Comment by AstridWinkler** [comment]
Résolution par Marwa MOHAMED : ajout du default et du selected disabled qui empêche la sélection de la valeur par défaut du select.
