### ISSUE TITLE
Tests Création d'un Article

### ISSUE THREAD

**Issue by LouiseW98** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#21]
Test de la commande "Création d'un article" dans le module "Administration du référentiel".

-Vérification que les champs sont fonctionnels
-Vérification que tous les champs sont présents
-Vérification des champs obligatoires
-Vérification que l'article est bien enregistré dans la base de données

**Comment by GomesLucie** [comment]
Vérification faites: 
-champs fonctionnels et aucun champs manquants
Le champs Numéro de référence (ou numéro unique) n'est pas sur le formulaire -> choix des programmeur, il sera donné automatiquement pas la base de données
Champs obligatoires : Désignation (nom courant pour l'article) et prix 
Champs facultatif : Description -> pas de limitation de caractères 

**_Vérification manquantes:_**
- que l'article est bien créer dans la base de données
- que un numéro unique est bien attribué
