### ISSUE TITLE
Tests Création d'une commande

### ISSUE THREAD

**Issue by LouiseW98** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#22]
Test de la commande "Création d'une commande" dans le module "Suivis de commandes".

-Vérification que les champs sont fonctionnels
-Vérification que tous les champs sont présents
-Vérification des champs obligatoires
-Vérification que l'article est bien enregistré dans la base de données

**Comment by GomesLucie** [comment]
possible de créer une commande sans moyen de paiement

**Comment by GomesLucie** [comment]
Nous avons oublié de donner la possibilité de créer un individu inconnu

**Comment by AstridWinkler** [comment]
Lorsqu'on sélectionne le moyen de payement "carte bancaire", la valeur du versement réalisé n'est pas demandé contrairement au payement par "chèque".

PB Précédent résolu : Lucie GOMES et Marwa MOHAMED

**Comment by AstridWinkler** [comment]
A moins que ce soit voulu du fait que le payement est sensé avoir été complété avant puisque commande en ligne.
Donc présence d'anomalies exclusivement à partir des fonctions de vérifications ?

**Comment by AstridWinkler** [comment]
Erreur de ma part, ce n'était pas un problème mais un parti-pris.
