### ISSUE TITLE
Chargement titre référenciel

### ISSUE THREAD

**Issue by GomesLucie** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#32]
Depuis la division des fichiers ejs référentiel, le titre et le bouton de recherches yoyotte un peu lorsque l'on clique rapidement sur la barre pour passer d'une fonctionnalité à l'autre.

**Comment by AstridWinkler** [comment]
Problème existant seulement lorsque l'on inspecte la page et qu'on passe d'une page  à l'autre rapidement. Si on inspecte pas, pas de problème.
