### ISSUE TITLE
Administration du référentiel: barre

### ISSUE THREAD

**Issue by LouiseW98** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#4]
Lorsque l'on clique sur un des éléments de la barre puis que l'on rempli le formulaire associé la barre blanche redevient verte.
Pas d'idée pour régler le problème pour le moment.

**Comment by GomesLucie** [comment]
Idée de résolution:
lorsque l'on clique sur un des input de la barre, on lui ajoute une classe qui lui attribut le css particulier (devient blanc).
et le seule moyen qu'il perde la classe c'est de quitter le module ou de cliquer sur un autre input de la barre.

**Comment by marwa-mohamed-dev** [comment]
Idée appliquée
problème réglé
