### ISSUE TITLE
Détails Input

### ISSUE THREAD

**Issue by GomesLucie** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#41]
Une fois toutes les fonctions réalisées. 
Pensez à vérifier les patterns de tous les input et à mettre des placeholders si besoin.
(surtout au niveau des input de création et de modifications)

**Comment by LouiseW98** [comment]
Pattern et placeholder mis pour tous les inputs du Module Administration du référentiel

**Comment by AstridWinkler** [comment]
Pattern tous mis en place et testé par moi-même et Marwa MOHAMED lors du test d'intégration.
Résolution par Louise WEBER et Lucie GOMES
