### ISSUE TITLE
Etat commande

### ISSUE THREAD

**Issue by GomesLucie** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#44]
Je pense qu'il faut donner un état aux commandes pour savoir si elle sont encore en cours de modification (Anomalie ou juste pas finis d'être tapé) ou si elles sont valides et qu'elles sont envoyé au centre de stockage.

Si des commandes font parties du deuxième cas, il faudra qu'on ne puisse plus y accéder depuis l'onglet modification de commande

**Comment by AstridWinkler** [comment]
J'ai résolu le problème en donnant à la variable booléenne "verification" une valeur false par défaut.
Cette valeur est modifiée en true lorsqu'une commande est créée manuellement et donc subies les vérifications quant à la présence d'anomalies (commande à rentrer entièrement carte commande postale).
Dans l'onglet "Modification de commande" devenu "Vérification de commande", on peut chercher puis observer les informations d'une commande ayant été effectuée en ligne, et donc avec verification = false.
Enfin on peut les valider, et qu'elles aient ou non une anomalie, verification passe à true.
