### ISSUE TITLE
Conflit de app.post dans Referentiel.ejs

### ISSUE THREAD

**Issue by AstridWinkler** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#5]
Date : 16/03/2021
Membre : Astrid WINKLER
Fichier : app.js / Referentiel.ejs

Dans Referentiel.js, on a fait le choix de n'avoir qu'un seul fichier ejs alors que cette page doit nous permettre de réaliser 4 actions (créer nouvel article, modifier article, créer nouvel individu, modifier individu).
Ces options sont graphiquement possibles grâce à <script> et l'appel de fonctions en fonction de l'endroit où on clique.
Cependant, lorsqu'on connecte les input à la base de donnée, on utilise deux actions de même type :
app.post('/referentiel', (req, res)..... ce qui renvoie une erreur en fonction de laquelle des fonctions est appelée en premier.

Résolution possible : passer à 4 fichiers ejs OU passer à 2 fichiers ejs avec créer nouvel article / modifier article d'un côté et créer nouvel individu / modifier individu de l'autre OU solution avec un seul fichier à trouver.

**Comment by marwa-mohamed-dev** [comment]
Séparation effectuée mais si on garde la même configuration visuel, si on est dans la page Article et qu'on appui sur créer un individu ou modifier un individu, le premier click correspond au changement de page et il faut reclicker pour faire apparaitre les éléments à l'intérieur

je n'ai pas réussi à faire exécuter les 2 actions à la fois

**Comment by marwa-mohamed-dev** [comment]
Proposition : ne plus avoir que 2 boutons : Gerer articles et Gérer indivius puis créer et modifier article/individu

**Comment by AstridWinkler** [comment]
Les changements dans les POST ont été fait : app.post('/referentiel/Individu') et app.post('/referentiel/Article') au lieu de app.post('/referentiel') pour les deux nouvelles pages.
PB du double clique toujours d'actualité

**Comment by JiouLee** [comment]
Problème du double clique remédié suite à la configuration déterminée pendant la réunion précédente.
Les changements sont dans la branche : Aministration_ref
Attente de validation dans "pull request".

**Comment by AstridWinkler** [comment]
Résolution finale : On revient à 4 fichiers séparés pour les 4 options (créer nouvel article / modifier article / créer nouvel individu / modifier individu), sinon conflit au niveau des fonctions appelées : on ne peut pas écrire de ejs <%= %> dans les fonctions, ce qui ne permet pas d'instaurer les fonctionnalités de type recherche et affichage de liste d'éléments issus de la base de données.
