### ISSUE TITLE
Numéro de téléphone type Number

### ISSUE THREAD

**Issue by AstridWinkler** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#54]
Un pattern a été utilisé pour rentrer le numéro de téléphone lorsqu'on créer un nouvel individu : pattern='[0]{1}[0-9]{9}'
Or le type étant un nombre (type = Number), lorsqu'on veut modifier un individu, le 0 est automatiquement enlevé par le système.
Il est a ajouté systématiquement par l'utilisateur sous faute d'erreur.

Solution possible : Donner un type String au numéro de téléphone.

**Comment by GomesLucie** [comment]
Changement fait, le 0 est bien présent.
