### ISSUE TITLE
Test intégration : Administration Ref

### ISSUE THREAD

**Issue by JiouLee** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#56]
Modifier Article :
- suppression d'article ne marche pas

Modifier Individu :
- Changement statut du client ne marche pas
- Premier '0' du numéro de téléphone disparait

**Comment by JiouLee** [comment]
Suite au nouveau pull :
Modifier Individu :
- Suppression ne marche plus
- Les deux problèmes plus hauts sont réglés

Modifier Article :
- Pas de changement

**Comment by AstridWinkler** [comment]
Le pattern de modifier un individu au niveau de sa désignation est très strict, et ne semble pas permettre d'entrer des chiffres.
pattern='[A-Z]{1}[a-z]{1,}'
Cela peut être embêtant et restrictif.

**Comment by marwa-mohamed-dev** [comment]
créer un individu 
**- label Nom à mettre en majuscule**
- les patterns des inputs fonctionnent correctement : 
     - Nom que en majuscule, seulement lettres, tiret et espace autorisés
     - Prénom première lettre en majuscule, seulement lettres, tiret et espace autorisés
     - Adresse : 
           - numéro de voie que des chiffres, max : 3 chiffres
           - nom de voie et ville : autorisés lettres, tirets, accents et espaces
           - code postal que des chiffres, obligatoirement 5 chiffres
     - numéro : 10 chiffres obligatoires
     - input de type mail 
**-  enlever prospect de caractéristiques commerciales (à faire partout)** 
- La création s'effectue bien

Modifier un individu
- Recherche fonctionne correctement : par nom de famille, par prénom, par date de naissance, nom et prénom, nom et date, prénom et date et les trois en même temps 
- la sélection d'un individu s'effectue correctement, on récupère bien tout les informations (sauf date de naissance)
**- problème au niveau du select ** 
- Les patterns sont bien présent comme dans la création
- La modification des information de l'individu s'effectue bien 
- L'annulation fonctionne correctement : en écrivant et appuyant sur annuler les modifications n'ont pas lieu 
- La suppression fonctionne correctement 
**- CSS buttons supprimer et annuler à refaire (peut être mettre plus en avant modifier pour faire la différence)**

créer un article
- les partterns fonctionnent presque tous correctement
  - Désignation :  que lettres, faut ajouter tirets, accent et espace
  - prix : que des chiffres, virgules ou points autorisés
  - image : choix du document depuis le poste fonctionne correctement. Mais tout type de document accepté et pas que image 
  - description : tout est autorisé
- La création s'effectue bien 

Modifier un article
- Recherche fonctionne correctement : par référence, par désignation et les deux en même temps 
- la selection d'un article s'effectue correctement, on récupère bien tout les informations 
- Les patterns sont bien presque tous présent comme dans la création
**- Pattern à rajouter à Désignation (même que pour créer un article)**
- La modification des information d'un article s'effectue bien 
- L'annulation fonctionne correctement : en écrivant et appuyant sur annuler les modifications n'ont pas lieu
- La suppression fonctionne correctement
**- CSS button supprimer et annuler à refaire (peut être mettre plus en avant modifier pour faire la différence)**

**Comment by AstridWinkler** [comment]
Problèmes résolus par Luice GOMES et Louise WEBER
Test d'intégration du module terminé : tout fonctionne
