### ISSUE TITLE
Remarque Cible de routage

### ISSUE THREAD

**Issue by marwa-mohamed-dev** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#58]
Quand on veut valider ou refuser une cible de routage, on peut ajouter une remarque, cependant je n'arrive pas à y accéder pour update la cible de routage et pouvoir la réutiliser.

**Comment by AstridWinkler** [comment]
PB résolu par Marwa MOHAMED
Création d'un petit formulaire qui permet d'avoir un bouton submit qui va appeler la méthode post d'intérêt.
