### ISSUE TITLE
Test d'intégration Prospection

### ISSUE THREAD

**Issue by JiouLee** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#59]
Créer une nouvelle cible de routage :
- Rendre obligatoire au moins choix d'un article
- Changement de "soumettre à validation" à "soumettre"

Valider une cible de routage :
- Mettre un tickbox pour choisir entre "valider" ou "refuser" au lieu d'appuyer puis appuyer sur "valider"

Envoyer une publicité :
- La page prend trop de temps à charger

**Comment by AstridWinkler** [comment]
Problèmes résolus par Marwa MOHAMED.
Test d'intégration complet : tout fonctionne.
