### ISSUE TITLE
Ajout moyen de paiement

### ISSUE THREAD

**Issue by GomesLucie** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#6]
Test unitaire des fonctions :paiementCarte() et paiementCheque()

On n'arrive pas à vérifier que les inputs de type "checkbox" sont bien coché et donc on ne peut pas ajouter le HTML à la page pour compléter les informations.

**Comment by marwa-mohamed-dev** [comment]
Problème devrait être réglé.
Changement de class en Id
