### ISSUE TITLE
test du Système de connexion à l'application

### ISSUE THREAD

**Issue by GomesLucie** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#7]
Mise en place d'une connexion personnalisé pour chaque employé de l'entreprise (avec un id et un password unique pour chacun).

**Comment by AstridWinkler** [comment]
Réalisation terminée
PB : encore connexion locale et pas de liaison avec la base de données

**Comment by GomesLucie** [comment]
**_Problèmes:_**
message d'erreur lorsque identifiant ou mdp incorrect peut visible

**Comment by AstridWinkler** [comment]
Vous en chargez vous Lucie ou Louise ? Ou souhaitez vous que j'y remédie ?

**Comment by GomesLucie** [comment]
on a déjà fait une première modif en mettant une petite image de panneau danger mais l'image ne s'affiche, je pull et je te laisse regarder si tu veux

**Comment by AstridWinkler** [comment]
Merci l'affichage me va, je laisse l'issue ouverte tant que le problème de l'image n'est pas résolu.

**Comment by AstridWinkler** [comment]
Les image sont à placer dans le folder public pour être accessibles, puis il suffit de modifier légèrement le trajet pour accéder à l'image.

**Comment by AstridWinkler** [comment]
Problème résolu par Lucie GOMES et Louise WEBER.

**Comment by AstridWinkler** [comment]
J'avais fermé mais il manque encore la liaison à la base de données, je m'y met dessus.
