### ISSUE TITLE
Restriction d'accès aux modules/fonctionnalités

### ISSUE THREAD

**Issue by GomesLucie** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#8]
2 méthodes (une à choisir) pour restreindre l'accès de certain modules aux employés selon leur statut (rôle) dans l'entreprise:

- ajout de mdp supplémentaire si on veut accéder à certaines fonctionnalités.
- ajout d'une caractéristique "numéro d'accès"  aux employés avec vérification que l'employé à bien ce numéro lorsqu'il clique sur une fonctionnalité

**Comment by AstridWinkler** [comment]
On part pour le moment sur l'option de numéro d'accès qui va être tester par le système pour confirmer ou pas l'accès à certaines pages demandant des autorisations précises.
En cours de codage

**Comment by AstridWinkler** [comment]
La restriction aux modules a été réalisé de manière locale en fonction du rôle de l'employé au sein de l'entreprise
