### ISSUE TITLE
Référenciel conflit méthode post

### ISSUE THREAD

**Issue by marwa-mohamed-dev** [marwa-mohamed-dev/marwa-mohamed-dev.github.io#9]
Dans la page de référentiel il est possible de créer un individu et créer un article. Pour cela les deux font appel à la méthode Post, ce qui créer une erreur

Solution trouvée ensemble : Séparer en 2 pages (lien différent) : Article et Individu tout en gardant le même visuel

**Comment by marwa-mohamed-dev** [comment]
Séparation effectuée mais si on garde la même configuration visuel, si on est dans la page Article et qu'on appui sur créer un individu ou modifier un individu, le premier click correspond au changement de page et il faut reclicker pour faire apparaitre les éléments à l'intérieur

je n'ai pas réussi à faire exécuter les 2 actions à la fois

**Comment by marwa-mohamed-dev** [comment]
Proposition : si on est dans Article, il faut revenir dans référenciel pour pouvoir aller dans Individu

**Comment by JiouLee** [comment]
> Proposition : si on est dans Article, il faut revenir dans référenciel pour pouvoir aller dans Individu

Les propositions ont été appliqué dans la branche : Administration_ref
Elle est actuellement en attente de confirmation dans le pull request.
